"""rename address

Revision ID: 625e39351571
Revises: f51f2e4d21b7
Create Date: 2024-04-15 18:27:21.287778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625e39351571'
down_revision = 'f51f2e4d21b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###

